# Generated by Django 3.1.6 on 2021-02-18 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
