# Generated by Django 3.1.7 on 2021-06-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20210626_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/avatars/default.png', upload_to='media/avatars'),
        ),
    ]
